# Generated by Django 3.0.6 on 2020-05-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
